Выход клиента + заготовка для чат-групп
VityasZV/JointPython pull request #29
Opened 2020-05-01 15:13 UTC by SamuilYu

1. При выходе клиента, клиент и сервер обмениваются парой сообщений, чтоб сервер не упал при чтении из неактивного сокета
2. Изменил некоторые базовые классы, чтоб поддерживалась работа с чат группами
3. Обработчик для создания групп, который информирует пользователей о том, что они были добавлены в группу
4. Изменил обработчик отправки, чтоб можно было отправлять в разные группы

2020-05-01 15:29 UTC, VityasZV commented on client/demo_client.py
> +        # a method for connecting to server
бессмысленный комментарий

2020-05-01 15:30 UTC, VityasZV commented on client/demo_client.py
> +        # a method for graceful disconnect
бессмысленный комментарий

2020-05-01 15:31 UTC, VityasZV commented on http_classes/base_classes.py
> +            "auth_token": self.auth_token
теперь это не выглядит красиво;( ахахах, ну да ладно

2020-05-01 15:34 UTC, SamuilYu commented on http_classes/base_classes.py
> +            "auth_token": self.auth_token
ахах, я вообще не помню, чтоб я это исправлял

возможно, pycharm отформатировал)

2020-05-01 15:35 UTC, VityasZV commented on http_classes/base_classes.py
> +            cursor = self.conn.cursor()
я для кого создал класс Курсор? используй with Cursor as бла бла бла

2020-05-01 15:36 UTC, VityasZV commented on http_classes/base_classes.py
> +            cursor.close()
я для кого создал класс Курсор? используй with Cursor as бла бла бла

2020-05-01 15:37 UTC, VityasZV commented on psql/users_to_chats.sql
> +commit;
не нужно ещё один файл ради 7 строчек, по логике относится к чатам - добавь туда

2020-05-01 15:39 UTC, SamuilYu commented on psql/users_to_chats.sql
> +commit;
я не согласен
я на самом деле верю, что так будет проще добавлять и удалять
я настаиваю на такой структуре БД

2020-05-01 15:40 UTC, VityasZV commented on psql/chats.sql
> +  admin varchar       -- массив пользователей данного чата.
поменяй комментарий к полю - что это создатель чата

2020-05-01 15:43 UTC, VityasZV commented on http_classes/base_classes.py
> +    def __setitem__(self, chat_name, receivers):
не понятно по коду что лежит в recievers, вот тут бы комментарий или явное указание типа как раз не помешало

2020-05-01 15:55 UTC, SamuilYu commented on http_classes/base_classes.py
> +    def __setitem__(self, chat_name, receivers):
метод  __setitem__ принимает два значения, поэтому в receivers передается сразу и админ и множество юзеров, которые будут принадлежать группе
добавлю пояснение в следующем коммите, в котором подправлю комментарии и кодстайл

2020-05-01 15:55 UTC, VityasZV commented on server/demo_server.py
> +        self._chat_groups['all'] = ("init", {login for login in self._users.keys()})
Здесь же кладется ChatGroup? вроде ты забыл это написать слева от (

2020-05-01 16:00 UTC, VityasZV commented on server/http_server.py
> +                        self.send_response(self._users[user].connection, resp)
наверное можно фигануть отдельную функцию вроде handle_response для подобных бродкастов.

2020-05-01 16:05 UTC, VityasZV commented on server/http_server.py
> +            self.send_response(connection, resp)
отдельная функция

2020-05-01 16:05 UTC, SamuilYu commented on server/demo_server.py
> +        self._chat_groups['all'] = ("init", {login for login in self._users.keys()})
Там подразумевалось так, но это уродливый вариант
Твой вариант изящнее - поменял

2020-05-01 16:06 UTC, SamuilYu commented on server/http_server.py
> +                        self.send_response(self._users[user].connection, resp)
да, хорошая идея
думал об этом, но решил повременить 
можем добавить в ишьюс

2020-05-01 16:07 UTC, SamuilYu commented on server/http_server.py
> +            self.send_response(connection, resp)
что имеешь в виду?

2020-05-01 16:08 UTC, SamuilYu commented on http_classes/base_classes.py
> +    def __setitem__(self, chat_name, receivers):
от recievers вообще избавлюсь
спасибо

2020-05-01 16:08 UTC, VityasZV commented on server/http_server.py
> +            if member != "init":
уже несколько раз вижу эту константу инит. Наверное её можно вынести в какую-нибудь констансту и написать за что она отвечает

2020-05-01 16:09 UTC, VityasZV commented on server/http_server.py
> +                        self.send_response(receiver.connection, resp)
отдельная функция

2020-05-01 16:09 UTC, SamuilYu commented on http_classes/base_classes.py
> +            cursor.close()
буду использовать

2020-05-01 16:11 UTC, VityasZV requested changes
отписал. Наверное я ещё запишу как-то документацию к хендлерам, а то путаться начнём.

2020-05-01 16:12 UTC, VityasZV commented on psql/users_to_chats.sql
> +commit;
так лол, я не спорю со структурой. Просто добавь эту таблицу в chats.sql

2020-05-01 16:12 UTC, SamuilYu commented on psql/users_to_chats.sql
> +commit;
или ты имеешь в виду, что скрипты можно объединить в один файл?
ну тогда уж все три надо в один скрипт

2020-05-01 16:14 UTC, VityasZV commented on server/http_server.py
> +            self.send_response(connection, resp)
то же самое что выше

2020-05-01 16:17 UTC, VityasZV commented on psql/users_to_chats.sql
> +commit;
ага, соглы

2020-05-01 16:23 UTC, SamuilYu commented on client/demo_client.py
> +        # a method for connecting to server
удалил

2020-05-01 16:23 UTC, SamuilYu commented on client/demo_client.py
> +        # a method for graceful disconnect
удалил

2020-05-01 16:24 UTC, SamuilYu commented on http_classes/base_classes.py
> +            cursor.close()
использовал

2020-05-01 16:24 UTC, SamuilYu commented on psql/users_to_chats.sql
> +commit;
я оставил в трех - пусть уже будет
как-нибудь поправим

2020-05-01 16:24 UTC, SamuilYu commented on psql/chats.sql
> +  admin varchar       -- массив пользователей данного чата.
поменял

2020-05-01 16:24 UTC, SamuilYu commented on http_classes/base_classes.py
> +    def __setitem__(self, chat_name, receivers):
избавился

2020-05-01 16:25 UTC, SamuilYu commented on server/demo_server.py
> +        self._chat_groups['all'] = ("init", {login for login in self._users.keys()})
сделал изящнее

2020-05-01 16:25 UTC, SamuilYu commented on server/http_server.py
> +            if member != "init":
добавил комментарий
строка - это уже константа))

2020-05-01 16:28 UTC, VityasZV commented on server/http_server.py
> +            if member != "init":
ну я имел в виду создать переменную, но да ладно ок

2020-05-01 16:30 UTC, VityasZV commented on http_classes/base_classes.py
>              cursor.close()
курсор закрывается автоматически, вызывая exit - строчку можно убрать.

2020-05-01 16:32 UTC, VityasZV commented on http_classes/base_classes.py
> +                cursor.close()
лишняя строчка

2020-05-01 16:34 UTC, VityasZV commented on http_classes/base_classes.py
> +        # receivers is a tuple of two containing an admin as a first and all other users as a second
теперь комент не нужен, и достаточно сделать group : ChatGroup - и всё будет понятно

2020-05-01 16:34 UTC, VityasZV commented on http_classes/base_classes.py
>              cursor.close()
лишняя строчка

2020-05-01 16:37 UTC, VityasZV commented on http_classes/base_classes.py
> +                cursor.close()
не нужно

2020-05-01 16:38 UTC, VityasZV requested changes
Cursor тем и хорошо что после with закрывает себя. Поэтому есть несколько лишних строк

2020-05-02 13:20 UTC, VityasZV approved these changes
вот сейчас вроде всё чики пуки, делаю squash and merge

2020-05-02 13:21 UTC, merged