add chatgroup admin capabilities
VityasZV/JointPython pull request #31
Opened 2020-05-06 07:43 UTC by SamuilYu

2020-05-08 21:29 UTC, VityasZV commented
посмотрю на днях, пока разреши конфликты

2020-05-12 09:54 UTC, VityasZV commented on server/http_server.py
> +        all_users = self._chat_groups[chat_name].users.copy()
не вижу использования all_users дальше

2020-05-12 10:00 UTC, VityasZV commented on http_classes/base_classes.py
> +            raise HTTPError(405, "The user does not exist")
404?

2020-05-12 10:01 UTC, VityasZV commented on http_classes/base_classes.py
> +            raise HTTPError(405, "The user does not exist")
и не существует чата а не пользователя

2020-05-12 10:02 UTC, VityasZV commented on server/http_server.py
> +        all_users = self._chat_groups[chat_name].users
не используешь

2020-05-12 10:03 UTC, VityasZV requested changes
либо чуть подкорректируй либо объясни почему ты прав

2020-05-12 10:20 UTC, SamuilYu commented on server/http_server.py
> +        all_users = self._chat_groups[chat_name].users
используется в broadcast

2020-05-12 10:21 UTC, SamuilYu commented on server/http_server.py
> +        all_users = self._chat_groups[chat_name].users.copy()
используется в broadcast

2020-05-12 10:23 UTC, SamuilYu commented on http_classes/base_classes.py
> +            raise HTTPError(405, "The user does not exist")
глаз-алмаз, сейчас исправлю)

2020-05-14 23:22 UTC, VityasZV commented on server/http_server.py
> +        all_users = self._chat_groups[chat_name].users
Сори) Я был слеп

2020-05-14 23:25 UTC, VityasZV approved these changes
Вроде бы всё хорошо. Правда я начинаю понемногу теряться в том как работают текущие хэндлеры.

2020-05-14 23:32 UTC, merged